name: flutter_torrent_streamer_example
description: Demonstrates how to use the flutter_torrent_streamer plugin.
publish_to: 'none'

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  drm_wv_fp_player: 0.0.3
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_torrent_streamer:
    path: ../

flutter:
  uses-material-design: true