name: flutter_torrent_streamer
description: A flutter plugin to stream videos directly from torrent&#x2F;magnet links.
version: 0.0.2
author: Sundeep Babbur <sundeep.sundeep11@gmail.com>
homepage: https://github.com/DarkSouL11/flutter_torrent_streamer

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: in.dotapps.plugins.flutter_torrent_streamer
    pluginClass: FlutterTorrentStreamerPlugin
